In [6]:
# import pandas as pd
# import pyodbc

# sql_query = """
#     WITH NOTIF AS (
#         SELECT DISTINCT
#             NOTIF.[NOTIF_ZZQMMODID_NotificationModificationId],
#             CHL.[CLINT_ClassNumberInternalKey],
#             CHL.[KLART_ClassTypeID],
#             CONCAT(CHL.[QMNUM_NotificationInternalKey],CHL.[FENUM_NotificationItemKey]) AS OBJEK,
#             CHL.[LRPID_LinearReferencePatternID],
#             NOTIF.[NOTIF_QMNUM_Notification],
#             NOTIF.[NOTIF_QMART_NotificationType],
#             NOTIF.[NOTIF_STRNO_FunctionalLocation],
#             STM.ThroughMetre AS StartTM,
#             ETM.ThroughMetre AS EndTM
#         -- notif characteristics. 
#         FROM [myANALYTICS_SP].[gold.fact.enterprise.asset].[vw_Fact_NotificationCharacteristicWithLinear] AS CHL
#         -- this is an inner join in the HANA query. However that was on SPM only view. This view has everything. I'm not really sure what the limitations of the HANA view are to be SPM only. So I haven't limited this one. 
#         INNER JOIN [myANALYTICS_SP].[gold.dimension.enterprise.asset].[vw_Dim_Notification] AS NOTIF ON CHL.[QMNUM_NotificationInternalKey] = NOTIF.[NOTIF_QMNUM_NotificationInternalKey]
#         -- these convert the KM data to Start and End through meters. These are then used in the final part of the query to return the SPM data. 
#         CROSS APPLY [config.enterprise.geospatial].[tf_KilometreToThroughMetre] ([LRPID_LinearReferencePatternID], FLOOR([START_POINT_LinearStartPointKM]), ([START_POINT_LinearStartPointKM]- FLOOR([START_POINT_LinearStartPointKM]))*1000) STM
#         CROSS APPLY [config.enterprise.geospatial].[tf_KilometreToThroughMetre] ([LRPID_LinearReferencePatternID], FLOOR([END_POINT_LinearEndPointKM]), ([END_POINT_LinearEndPointKM]- FLOOR([END_POINT_LinearEndPointKM]))*1000) ETM
#         WHERE 
#             CHL.[KLART_ClassTypeID] = '015' 
#             AND CHL.[CLINT_ClassNumberInternalKey] = '0000001726' 
#             AND NOTIF.[NOTIF_QMART_NotificationType] = 'N4' 
#             -- you do not need to filter on POSNR because the values are returned in columns below. 
#     )

#     SELECT NOTIF.*
#     -- These are the POSNR values as columns 
#         ,SPM.ID
#         ,SPM.ScopePushed
#         ,SPM.AssetClass
#         ,SPM.Program
#         ,SPM.SAPWBSNumber
#         ,SPM.ScopeSubset
#         ,SPM.ScopeQuantity
#         ,SPM.LSC
#         ,SPM.StartStation
#         ,SPM.EndStation
#         ,SPM.Road
#         ,SPM.FARID
#         ,SPM.Rail
#         ,SPM.FYEstimate
#         ,SPM.CriticalitySingleTrack
#         ,SPM.CriticalityTotalTrack
#         ,SPM.CRA
#         ,SPM.BaselineDate
#         ,SPM.CommissioningDate
#         ,SPM.ExpectedReplacementDate
#         ,SPM.DesignLife
#         ,SPM.CostofReplacement
#         ,SPM.LastInspectionCondition
#         ,SPM.LastInspectionDate
#         ,SPM.Program2
#         ,SPM.RIGSubmissionDate
#         ,SPM.LatestRenewalDate
#         ,SPM.RIGTableCategory
#         ,SPM.SleeperQuantity
#         ,SPM.RailQuantity
#         ,SPM.TrackKM
#         ,SPM.RailKM 
#         ,SPM.StartThroughmetre
#         ,SPM.EndThroughmetre
#     FROM NOTIF
#     CROSS APPLY [gold.belowrail.asset.track.ringfenced].[tf_ScopePriorityModel] ([LRPID_LinearReferencePatternID], StartTM, EndTM) SPM
#     -- filtering to 2024
#     -- WHERE SPM.FinancialYear = '2024'
# """

# # Define your server name
# server_name = 'myanalytics.aurizon.com.au'

# # Establish a connection using Windows Authentication
# conn = pyodbc.connect('DRIVER={SQL Server};SERVER=' + server_name + ';DATABASE=myANALYTICS_SP;Trusted_Connection=yes;')

# # Execute the SQL query and load the result into a pandas DataFrame
# df1 = pd.read_sql_query(sql_query, conn)

# df1.to_pickle("pkl/asset_renewal.pkl")
# # Display the DataFrame
# df1

C:\Users\r893859\AppData\Local\Temp\ipykernel_1928\2799121084.py:80: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql_query(sql_query, conn)

,NOTIF_ZZQMMODID_NotificationModificationId,CLINT_ClassNumberInternalKey,KLART_ClassTypeID,OBJEK,LRPID_LinearReferencePatternID,NOTIF_QMNUM_Notification,NOTIF_QMART_NotificationType,NOTIF_STRNO_FunctionalLocation,StartTM,EndTM,...,Program2,RIGSubmissionDate,LatestRenewalDate,RIGTableCategory,SleeperQuantity,RailQuantity,TrackKM,RailKM,StartThroughmetre,EndThroughmetre
0,MAJOR-2026-000001,0000001726,015,0020001380100001,BW-01ML,2000138010,N4,BW-01ML,88373.5366,89451.7941,...,MAINLINE C01,None,20260630,28,None,None,None,None,86411.7553,88626.5366
1,MAJOR-2026-000001,0000001726,015,0020001380100001,BW-01ML,2000138010,N4,BW-01ML,88373.5366,89451.7941,...,MAINLINE C01,None,20260630,28,None,None,None,None,88626.5366,93805.3716
2,MAJOR-2024-000001,0000001726,015,0020000523960001,GA-02ML,2000052396,N4,GA-02ML,8072.8011,8542.8011,...,MAINLINE C01,None,20240630,28,None,None,None,None,6287.0390,8531.8011
3,MAJOR-2024-000001,0000001726,015,0020000945320001,GA-02ML,2000094532,N4,GA-02ML,139042.0040,139072.0040,...,TURNOUT C13,None,20240630,29,None,None,None,None,139056.0040,139105.0040
4,MAJOR-2025-000001,0000001726,015,0020001157780001,GA-25CT,2000115778,N4,GA-25CT,30.1956,40.1956,...,TURNOUT C13,None,20260630,29,None,None,None,None,5.0000,58.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1205,MAJOR-2024-000001,0000001726,015,0020000949650001,GA-01ML,2000094965,N4,GA-01ML,61013.8843,62829.6274,...,MAINLINE C01,None,20240630,28,None,None,None,None,58841.0953,61141.8843
1206,MAJOR-2024-000001,0000001726,015,0020000949650001,GA-01ML,2000094965,N4,GA-01ML,61013.8843,62829.6274,...,MAINLINE C01,None,20240630,28,None,None,None,None,61141.8843,62949.6274
1207,MAJOR-2023-000001,0000001726,015,0020000707220001,GA-01ML,2000070722,N4,CV002890,27748.1272,30575.6391,...,MAINLINE C01,None,20260630,28,None,None,None,None,30568.6391,32338.3327
1208,MAJOR-2025-000001,0000001726,015,0020001156330001,MA-01ML,2000115633,N4,MA-01ML,21899.7041,21949.7041,...,TURNOUT C13,None,20250630,29,None,None,None,None,21863.7041,21905.7041
1209,MAJOR-2025-000001,0000001726,015,0020001156330001,MA-01ML,2000115633,N4,MA-01ML,21899.7041,21949.7041,...,C14 ADJOINING TURNOUT,None,20250630,34,None,None,None,None,21905.7041,21955.7041

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

df1 = pd.read_pickle('pkl/asset_renewal.pkl')

df1 = df1[['NOTIF_QMNUM_Notification', 'NOTIF_STRNO_FunctionalLocation', 'Program2', 'Program', 'FYEstimate']].sort_values(by='NOTIF_STRNO_FunctionalLocation')
df1

,NOTIF_QMNUM_Notification,NOTIF_STRNO_FunctionalLocation,Program2,Program,FYEstimate
604,2000114132,AP100112,MAINLINE C01,Planned Undercutting,2800784
1158,2000052258,AP100253,MAINLINE C01,Planned Undercutting,3548524.16
219,2000094585,AP100303,MAINLINE C01,Planned Undercutting,3548524.16
404,2000103896,AP100303,MAINLINE C01,Planned Undercutting,3548524.16
51,2000114134,AP100303,MAINLINE C01,Planned Undercutting,3548524.16
...,...,...,...,...,...
1027,2000104198,TO000958,TURNOUT C13,Planned Undercutting,136062
571,2000104256,TO000994,TURNOUT C13,Planned Undercutting,210000
764,2000138241,TO001173,C14 ADJOINING TURNOUT,Planned Undercutting,2547
36,2000094400,TO001174,TURNOUT C13,Planned Undercutting,127591
1190,2000094442,TO001222,TURNOUT C13,Planned Undercutting,118289

In [3]:
len(df1['NOTIF_STRNO_FunctionalLocation'].unique())

258

In [9]:
# Getting all FLOC from [vw_Dim_FunctionalLocation] where CompanyCode = 5000 -> df2_no_length

import pyodbc

sql_query = """
    SELECT
        FLOC_TPLNR_FunctionalLocationInternalKey,
        FLOC_STRNO_FunctionalLocation,
        FLOC_PLTXT_FunctionalLocationDescr,
        FLOC_TYPTX_FunctionalLocationCategoryDescr,
        FLOC_EQART_TechnicalObjectType,
        FLOC_EARTX_TechnicalObjectTypeDescr,
        FLOC_BUKRS_CompanyCode,
        FLOC_STORT_Location,
        FLOC_STORT_LocationDescr
    FROM [myANALYTICS_SP].[silver.dimension.enterprise.asset].[vw_Dim_FunctionalLocation]
	WHERE FLOC_BUKRS_CompanyCode = '5000'
	ORDER BY FLOC_STRNO_FunctionalLocation
"""

# Define your server name
server_name = 'myanalytics.aurizon.com.au'

# Establish a connection using Windows Authentication
conn = pyodbc.connect('DRIVER={SQL Server};SERVER=' + server_name + ';Trusted_Connection=yes;')

# Execute the SQL query and load the result into a pandas DataFrame
df2 = pd.read_sql_query(sql_query, conn)

# Display the DataFrame
df2

C:\Users\r893859\AppData\Local\Temp\ipykernel_1928\3305919067.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql_query(sql_query, conn)

,FLOC_TPLNR_FunctionalLocationInternalKey,FLOC_STRNO_FunctionalLocation,FLOC_PLTXT_FunctionalLocationDescr,FLOC_TYPTX_FunctionalLocationCategoryDescr,FLOC_EQART_TechnicalObjectType,FLOC_EARTX_TechnicalObjectTypeDescr,FLOC_BUKRS_CompanyCode,FLOC_STORT_Location,FLOC_STORT_LocationDescr
0,?0100000000000387769,AC-01CH,CALLEMONDAH BLUE ROAD 1,Track,10003,Yard Track,5000,CA0089,Callemondah
1,?0100000000000365741,AC-01JN,Jilalan Provisioning 1,Track,10003,Yard Track,5000,JI0204,Jilalan
2,?0100000000000366347,AC-01JN-JNJN,Jilalan Provisioning 1,Track,999999,Lvl 3 Segmentation,5000,JI0204,Jilalan
3,?0100000000000377748,AC-01NA,NOGOA YARD BLUE ROAD TRACK 1,Track,10003,Yard Track,5000,NO0275,Nogoa-Yamala
4,?0100000000000387811,AC-01PA,PARANA BLUE ROAD MAINLINE,Track,10001,Main Line,5000,PA0289,Parana
...,...,...,...,...,...,...,...,...,...
174219,?0100000000000253349,WL000203,Baralaba WB Strain Gauge Equip 4.225Km,Telecommunications,40000,Wayleave Objects,5000,BA0032,Baralaba
174220,?0100000000000253351,WL000204,Baralaba WB Location Box 4.225Km,Telecommunications,40000,Wayleave Objects,5000,BA0032,Baralaba
174221,?0100000000000253372,WL000205,Baralaba WB Location Box 4.165Km,Telecommunications,40000,Wayleave Objects,5000,BA0032,Baralaba
174222,?0100000000000264822,WL999999,Electric WLNL 01CR BYAA16.652Km,Bridges and other Structures,40000,Wayleave Objects,5000,AR0021,Armuna-Buckley
174223,?0100000000000265380,XX100013-01,Bridge 9.280km TRACK 1,Bridges and other Structures,20010,Bridges,5000,,None

In [14]:
df2 = df2[['FLOC_STRNO_FunctionalLocation', 'FLOC_EARTX_TechnicalObjectTypeDescr']].sort_values(by='FLOC_STRNO_FunctionalLocation')
df2

       FLOC_STRNO_FunctionalLocation FLOC_EARTX_TechnicalObjectTypeDescr
0                            AC-01CH                          Yard Track
1                            AC-01JN                          Yard Track
2                       AC-01JN-JNJN                  Lvl 3 Segmentation
3                            AC-01NA                          Yard Track
4                            AC-01PA                           Main Line
...                              ...                                 ...
174219                      WL000203                    Wayleave Objects
174220                      WL000204                    Wayleave Objects
174221                      WL000205                    Wayleave Objects
174222                      WL999999                    Wayleave Objects
174223                   XX100013-01                             Bridges

[174224 rows x 2 columns]

In [23]:
merged_df = pd.merge(df1, df2, how='left', left_on='NOTIF_STRNO_FunctionalLocation', right_on='FLOC_STRNO_FunctionalLocation')

merged_df = merged_df[['FLOC_EARTX_TechnicalObjectTypeDescr', 'FYEstimate']].sort_values(by='FLOC_EARTX_TechnicalObjectTypeDescr')
merged_df['FLOC_EARTX_TechnicalObjectTypeDescr'] = merged_df['FLOC_EARTX_TechnicalObjectTypeDescr'].astype(str)
merged_df['FYEstimate'] = merged_df['FYEstimate'].astype(float)
merged_df

     FLOC_EARTX_TechnicalObjectTypeDescr  FYEstimate
1096                              Cables  3167176.00
1087                              Cables  1919467.00
1086                              Cables  1273583.00
1085                              Cables  2261778.93
1084                              Cables  1350957.81
...                                  ...         ...
907                                  nan  1743638.93
908                                  nan   777408.58
909                                  nan  2534210.00
910                                  nan   177891.00
911                                  nan   195477.00

[1210 rows x 2 columns]

In [26]:
average_renewal_cost = merged_df.groupby('FLOC_EARTX_TechnicalObjectTypeDescr')['FYEstimate'].mean().reset_index()
pd.options.display.float_format = '{:.2f}'.format

average_renewal_cost

   FLOC_EARTX_TechnicalObjectTypeDescr  FYEstimate
0                               Cables  1122351.03
1                     Connecting Track   210000.00
2                   Corridor Access Pt  2933967.71
3                           Crossovers   523192.22
4                             Culverts   184439.12
5                  Curves - Lrg Radius  2033215.68
6                  Curves - Med Radius  1852874.22
7                  Curves - Sml Radius  1682299.42
8                   Electrical Turnout   773029.45
9                                 Fork    18157.00
10                       HV Protection  1853593.90
11                    Loading Facility   686190.52
12                           Main Line  1332652.35
13                      Manual Turnout   407705.30
14                      Network Router   337485.00
15                        Passing Loop    46979.77
16                          Private LX   996627.62
17                           Public LX  1694214.89
18                     Structure Track   820631.42
19                          Substation  1618406.31
20                       Tangent Track  1889620.57
21                         Transformer  1273583.00
22                  Unloading Facility   529958.32
23                          Yard Track    67884.58
24                                 nan  1029491.94

In [27]:
file_path = 'csv/average_renewal_cost.csv'
average_renewal_cost.to_csv(file_path, index=True)