In [63]:
# Getting all possible ActivityCode from Excel file -> df1

import pandas as pd

file_path = 'MaintenanceActivityTypes.xlsx'
sheet_name = 'in'

df1 = pd.read_excel(file_path, sheet_name=sheet_name, engine='openpyxl')
# df1 = df1[df1['Ignore'] != 1]

df1_split = df1.assign(TechnicalObjects_split=df1['TechnicalObjects'].str.split(', ')).explode('TechnicalObjects_split')
df1_split

,Index,ActivityCode,Maintenance Product,Frequency Required,Frequency Unit,TechnicalObjects,Ignore,Specifics,Unnamed: 8,Unnamed: 9,TechnicalObjects_split
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Main Line
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Passing Loop
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Loading Facility
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Unloading Facility
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Fork
...,...,...,...,...,...,...,...,...,...,...,...
156,1.0,"T24, T25",Earth Grid Inspections,260.0,Weeks,Earthing and Bonding,NaN,NaN,NaN,NaN,Earthing and Bonding
157,1.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",6.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
158,2.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",12.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
159,3.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",60.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
160,4.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",NaN,Fix on failure,NaN,1.0,NaN,NaN,NaN,NaN

In [ ]:
# Getting all possible ActivityCode from Excel file -> df1

import pandas as pd

file_path = 'MaintenanceActivityTypes.xlsx'
sheet_name = 'in'

df1 = pd.read_excel(file_path, sheet_name=sheet_name, engine='openpyxl')
# df1 = df1[df1['Ignore'] != 1]

df1_split = df1.assign(TechnicalObjects_split=df1['TechnicalObjects'].str.split(', ')).explode('TechnicalObjects_split')
df1_split

,Index,ActivityCode,Maintenance Product,Frequency Required,Frequency Unit,TechnicalObjects,Ignore,Specifics,Unnamed: 8,Unnamed: 9,TechnicalObjects_split
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Main Line
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Passing Loop
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Loading Facility
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Unloading Facility
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Fork
...,...,...,...,...,...,...,...,...,...,...,...
156,1.0,"T24, T25",Earth Grid Inspections,260.0,Weeks,Earthing and Bonding,NaN,NaN,NaN,NaN,Earthing and Bonding
157,1.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",6.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
158,2.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",12.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
159,3.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",60.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
160,4.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",NaN,Fix on failure,NaN,1.0,NaN,NaN,NaN,NaN

In [ ]:
# Getting all possible ActivityCode from Excel file -> df1

import pandas as pd

file_path = 'MaintenanceActivityTypes.xlsx'
sheet_name = 'in'

df1 = pd.read_excel(file_path, sheet_name=sheet_name, engine='openpyxl')
# df1 = df1[df1['Ignore'] != 1]

df1_split = df1.assign(TechnicalObjects_split=df1['TechnicalObjects'].str.split(', ')).explode('TechnicalObjects_split')
df1_split

,Index,ActivityCode,Maintenance Product,Frequency Required,Frequency Unit,TechnicalObjects,Ignore,Specifics,Unnamed: 8,Unnamed: 9,TechnicalObjects_split
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Main Line
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Passing Loop
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Loading Facility
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Unloading Facility
0,1.0,"C01, C14, C20, C02",Ballast Undercutting,600.0,MNT,"Main Line, Passing Loop, Loading Facility, Unl...",NaN,NaN,NaN,NaN,Fork
...,...,...,...,...,...,...,...,...,...,...,...
156,1.0,"T24, T25",Earth Grid Inspections,260.0,Weeks,Earthing and Bonding,NaN,NaN,NaN,NaN,Earthing and Bonding
157,1.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",6.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
158,2.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",12.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
159,3.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",60.0,Months,NaN,1.0,NaN,NaN,NaN,NaN
160,4.0,NaN,"Trackside Buildings, Hardstands, Electrical Re...",NaN,Fix on failure,NaN,1.0,NaN,NaN,NaN,NaN

In [64]:
file_path = 'AssetsTypes.xlsx'
sheet_name = 'in'

asset_types_df = pd.read_excel(file_path, sheet_name=sheet_name, engine='openpyxl')

asset_types_df

    AssetCode             AssetType
0                               NaN
1       10000         Track Objects
2       10001             Main Line
3       10003            Yard Track
4       10004      Loading Facility
..        ...                   ...
253   WATRPMP    Water Pumping Unit
254   WEASTSY  Weather Station Syst
255  WHEELSET              Wheelset
256   WLDRFBT    Welder: Flash-Butt
257   WLDRGEN       Welder: General

[258 rows x 2 columns]

In [100]:
# %%timeit
# {col: sum(df1_split['TechnicalObjects_split'] == col) for col in asset_types_df['AssetType']}

29 ms Â± 2.81 ms per loop (mean Â± std. dev. of 7 runs, 10 loops each)

In [101]:
# %%timeit
# test = {}
# for col in asset_types_df['AssetType']:
#     test[col] = sum(df1_split['TechnicalObjects_split'] == col)

26.3 ms Â± 387 Âµs per loop (mean Â± std. dev. of 7 runs, 10 loops each)

:

In [99]:
res = {col: sum(df1_split['TechnicalObjects_split'] == col) for col in asset_types_df['AssetType']}
counts = pd.DataFrame({
    'AssetType': res.keys(),
    'Count': res.values()
})
counts

                AssetType  Count
0                     NaN      0
1           Track Objects      0
2               Main Line     14
3              Yard Track      9
4        Loading Facility     12
..                    ...    ...
251    Water Pumping Unit      0
252  Weather Station Syst      3
253              Wheelset      0
254    Welder: Flash-Butt      0
255       Welder: General      0

[256 rows x 2 columns]

In [97]:
zero_counts = counts[counts['Count'] == 0]
zero_counts

              AssetType  Count
0                   NaN      0
1         Track Objects      0
9            Crossovers      0
11        Track Signage      0
16          Track Angle      0
..                  ...    ...
250    Wagon: Passenger      0
251  Water Pumping Unit      0
253            Wheelset      0
254  Welder: Flash-Butt      0
255     Welder: General      0

[149 rows x 2 columns]

In [98]:
with pd.ExcelWriter('test.xlsx', mode='w', engine='openpyxl') as writer:
    # Write the DataFrame to the Excel file
    zero_counts.to_excel(writer, sheet_name='zero_count', index=False)