## Read in All Tonnage

-- This notebook has a few key functions:
1. Read in an existing csv called "Complete Aggregate Tonnage" which is from the TonnageFiles folder 
2.  Read in a list of entire flocs called "flocts_list.pkl" which is in the main structure
3.  Read in a csv called "Complete Conversion Linecodes" which is a csv in the main structure
    * (2) and (3) become a merged output called "flocs_joined_to_linecode"
4.  Read in "asset_renewal_all_11032024" which is the entire pkl file provided by Mike King 
    * (4) gets joined with the result for (2+3) along with (1) for tonnage 
    * result is called "nsap_renewal_assets_linked"
5.  Read in "AllFLOCMaintenanceRequirementAndAVGCost" which is the entire pkl file provided by Huy Nguyen
    * (5) gets joined with the result for (2+3) along with (1) for tonnage
    * result is called nsap_maintenance_assets_linked
    * This is the file that needs to be replace with an updated version from Huy once he can run the script that converts Jane's linkage into his maintenance format. 
    * If the format isnt clear, review the existing "AllFLOCMaintenanceRequirementAndAVGCost" file and it will become familiar as to what the format needs to be

In [1]:
import pandas as pd

## 1. Read in an existing csv called "Complete Aggregate Tonnage" which is from the TonnageFiles folder

In [2]:
df = pd.read_csv("/workspaces/ds08-network-strategic-asset-plan-v2/TonnageFiles/Complete_Aggregate_Tonnage.csv")
df = df.rename(columns = { "DESCRIPTION":"FLOC_STORT_LocationDescr"})
df["FLOC_STORT_LocationDescr"] = df["FLOC_STORT_LocationDescr"].str.lower()
df

,System,LineCode,FilePath,FLOC_STORT_LocationDescr,2050.0,2049.0,2048.0,2047.0,2046.0,2045.0,...,1980.0,1979.0,1978.0,1977.0,1976.0,1975.0,1974.0,1973.0,1972.0,1971.0
0,ML,451,/workspaces/ds08-network-strategic-asset-plan-...,parana- callemondah,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ML,433,/workspaces/ds08-network-strategic-asset-plan-...,callemondah-byelle,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ML,499,/workspaces/ds08-network-strategic-asset-plan-...,barney point loop & yard,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ML,750,/workspaces/ds08-network-strategic-asset-plan-...,parana coal connection,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ML,450,/workspaces/ds08-network-strategic-asset-plan-...,parana- north coast line connection,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279,3H,311,/workspaces/ds08-network-strategic-asset-plan-...,pring to abbott point,32.9,33.8,34.4,34.9,35.3,35.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1280,3H,384,/workspaces/ds08-network-strategic-asset-plan-...,pring to abbott point,32.9,33.8,34.4,34.9,35.3,35.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1281,3H,204,/workspaces/ds08-network-strategic-asset-plan-...,north coast line connection (bowen-pring),0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1282,3H,206,/workspaces/ds08-network-strategic-asset-plan-...,north coast line connection (bowen-north),0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1283,3H,207,/workspaces/ds08-network-strategic-asset-plan-...,north coast line connection (townsville-south),0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2.  Read in a list of entire flocs called "flocts_list.pkl" which is in the main structure

In [3]:
df_floc = pd.read_pickle("/workspaces/ds08-network-strategic-asset-plan-v2/flocs_list.pkl")
df_floc["FLOC_STORT_LocationDescr"] = df_floc["FLOC_STORT_LocationDescr"].str.lower()
df_floc

,FLOC_STRNO_FunctionalLocation,FLOC_PLTXT_FunctionalLocationDescr,FLOC_TPLNR_FunctionalLocationInternalKey,FLOC_EARTX_TechnicalObjectTypeDescr,FLOC_MSGRP_FunctionalLocationRoom,FLOC_STORT_LocationDescr
0,PSG-CTSU-DECOMMISSIONED,DECOMMISSIONED EQUIPMENT,?0100000000000000562,None,,mayne
1,PN-TM-TA-MMT011,MMT011 TAMPER-SPOT TAMPER,?0100000000000005903,Tamping Machine,,gladstone infrastructure maintenance
2,PN-TM-TA-MMT011-EL01,24 VOLT DC SYSTEM,?0100000000000005904,Engine,,gladstone infrastructure maintenance
3,PN-TM-TA-MMT011-PN01,PNEUMATICS SYSTEM,?0100000000000005907,None,,gladstone infrastructure maintenance
4,PN-TM-TA-MMT011-ST01,MAIN FRAME STRUCTURAL,?0100000000000005908,Misc. Equipment,,gladstone infrastructure maintenance
...,...,...,...,...,...,...
157844,LX020257-93,Private Access Road - Rail Details,?0100000000000392628,Private LX,GA-05CR,mount mclaren
157845,LX020257-94,Private Access Road - Flangeways,?0100000000000392629,Private LX,GA-05CR,mount mclaren
157846,LX020257-95,Private Access Road - Gates,?0100000000000392630,Private LX,GA-05CR,mount mclaren
157847,LX020257-96,Private Access Road - Vegetation,?0100000000000392631,Private LX,GA-05CR,mount mclaren
157848,LX020257-93-01,Private Access Road - Track 1,?0100000000000392632,LX_RAIL_DETAILS,GA-05CR,mount mclaren

In [4]:
df_floc["FLOC_STORT_LocationDescr"] = df_floc["FLOC_STORT_LocationDescr"].str.replace(' ', '')
df_floc["FLOC_STORT_LocationDescr"] = df_floc["FLOC_STORT_LocationDescr"].str.replace('\s', '')
df_floc["FLOC_STORT_LocationDescr"] = df_floc["FLOC_STORT_LocationDescr"].str.replace('\W', '')
df_floc["FLOC_STORT_LocationDescr"] = df_floc["FLOC_STORT_LocationDescr"].str.replace('-', '')
df_floc

,FLOC_STRNO_FunctionalLocation,FLOC_PLTXT_FunctionalLocationDescr,FLOC_TPLNR_FunctionalLocationInternalKey,FLOC_EARTX_TechnicalObjectTypeDescr,FLOC_MSGRP_FunctionalLocationRoom,FLOC_STORT_LocationDescr
0,PSG-CTSU-DECOMMISSIONED,DECOMMISSIONED EQUIPMENT,?0100000000000000562,None,,mayne
1,PN-TM-TA-MMT011,MMT011 TAMPER-SPOT TAMPER,?0100000000000005903,Tamping Machine,,gladstoneinfrastructuremaintenance
2,PN-TM-TA-MMT011-EL01,24 VOLT DC SYSTEM,?0100000000000005904,Engine,,gladstoneinfrastructuremaintenance
3,PN-TM-TA-MMT011-PN01,PNEUMATICS SYSTEM,?0100000000000005907,None,,gladstoneinfrastructuremaintenance
4,PN-TM-TA-MMT011-ST01,MAIN FRAME STRUCTURAL,?0100000000000005908,Misc. Equipment,,gladstoneinfrastructuremaintenance
...,...,...,...,...,...,...
157844,LX020257-93,Private Access Road - Rail Details,?0100000000000392628,Private LX,GA-05CR,mountmclaren
157845,LX020257-94,Private Access Road - Flangeways,?0100000000000392629,Private LX,GA-05CR,mountmclaren
157846,LX020257-95,Private Access Road - Gates,?0100000000000392630,Private LX,GA-05CR,mountmclaren
157847,LX020257-96,Private Access Road - Vegetation,?0100000000000392631,Private LX,GA-05CR,mountmclaren
157848,LX020257-93-01,Private Access Road - Track 1,?0100000000000392632,LX_RAIL_DETAILS,GA-05CR,mountmclaren

## 3.  Read in a csv called "Complete Conversion Linecodes" which is a csv in the main structure

In [5]:
df_entire = pd.read_csv("/workspaces/ds08-network-strategic-asset-plan-v2/Conversion_Complete_LineCodes.csv", header=0)
df_entire.columns = ["System", "FLOC_STORT_LocationDescr", "LineCode"]
df_entire = df_entire.dropna()
df_entire

          System       FLOC_STORT_LocationDescr LineCode
1     Blackwater  CMONDAH 282C/D Pts-296A/B Pts    NC454
2     Blackwater   CMONDAH 294A/B Pts-MT MILLER    NC455
3     Blackwater                      MT MILLER    NC455
4     Blackwater               MT MILLER-YARWUN    NC236
5     Blackwater                         YARWUN    NC237
...          ...                            ...      ...
1000    Newlands     NEWLANDS JCT-NEWLANDS MINE    NB380
1001    Newlands           ARR RD NEWLANDS MINE    NB380
1002    Newlands           DEP RD NEWLANDS MINE    NB380
1004    Newlands              BOS NEWLANDS MINE    NB380
1006    Newlands                  C RD MERINDA     NN204

[697 rows x 3 columns]

In [6]:
df_entire["FLOC_STORT_LocationDescr"] = df_entire["FLOC_STORT_LocationDescr"].str.lower()
df_entire["FLOC_STORT_LocationDescr"] = df_entire["FLOC_STORT_LocationDescr"].str.replace(' ', '')
df_entire["FLOC_STORT_LocationDescr"] = df_entire["FLOC_STORT_LocationDescr"].str.replace('\s', '')
df_entire["FLOC_STORT_LocationDescr"] = df_entire["FLOC_STORT_LocationDescr"].str.replace('\W', '')
df_entire["FLOC_STORT_LocationDescr"] = df_entire["FLOC_STORT_LocationDescr"].str.replace('-', '')
df_entire

          System   FLOC_STORT_LocationDescr LineCode
1     Blackwater  cmondah282c/dpts296a/bpts    NC454
2     Blackwater   cmondah294a/bptsmtmiller    NC455
3     Blackwater                   mtmiller    NC455
4     Blackwater             mtmilleryarwun    NC236
5     Blackwater                     yarwun    NC237
...          ...                        ...      ...
1000    Newlands    newlandsjctnewlandsmine    NB380
1001    Newlands          arrrdnewlandsmine    NB380
1002    Newlands          deprdnewlandsmine    NB380
1004    Newlands            bosnewlandsmine    NB380
1006    Newlands                 crdmerinda    NN204

[697 rows x 3 columns]

In [7]:
complete = pd.merge(df_floc, df_entire, on = "FLOC_STORT_LocationDescr", how = 'left')
complete = complete.loc[complete["LineCode"].notnull()]

In [8]:
complete.to_pickle("DataFiles/flocs_joined_to_linecode.pkl")

## 4.  Read in "asset_renewal_all_11032024" which is the entire pkl file provided by Mike King 
    * (4) gets joined with the result for (2+3) along with (1) for tonnage

In [9]:
renewal = pd.read_pickle("/workspaces/ds08-network-strategic-asset-plan-v2/asset_renewal_all_11032024.pkl")
renewal = renewal.rename(columns = {"FuncLocID":"FLOC_STRNO_FunctionalLocation"})
renewal

,FLOC_STRNO_FunctionalLocation,Asset Type,Asset,FuncLocLinearLengthKM,Life,Life Unit,Unit,YEAR_OF_CONSTRUCTION
0,LX000659-95,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN
1,LX000661-91,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN
2,LX000750,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN
3,LX000640,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN
4,LX000758,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN
...,...,...,...,...,...,...,...,...
4791,ST009540-02,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN
4792,ST009510-02,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN
4793,ST007820-04,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN
4794,ST007870-02,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN
4795,ST008530-04,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN

In [10]:
model_testrun_1 = pd.merge(renewal, complete, on = "FLOC_STRNO_FunctionalLocation", how = "left")
model_testrun_1.loc[model_testrun_1["LineCode"].notnull()] #this doesnt store the output so nulls still included

,FLOC_STRNO_FunctionalLocation,Asset Type,Asset,FuncLocLinearLengthKM,Life,Life Unit,Unit,YEAR_OF_CONSTRUCTION,FLOC_PLTXT_FunctionalLocationDescr,FLOC_TPLNR_FunctionalLocationInternalKey,FLOC_EARTX_TechnicalObjectTypeDescr,FLOC_MSGRP_FunctionalLocationRoom,FLOC_STORT_LocationDescr,System,LineCode
0,LX000659-95,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN,Bowen Developmental Road - Gates,?0100000000000325398,Public LX,NL-01CR,binbeebriaba,Newlands,NL846
1,LX000661-91,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN,Ardurad Rd Pedestrian Dn - Controls,?0100000000000325320,Public LX,BW-03CR,blackwater,Blackwater,CL777\nCL778
2,LX000750,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN,LX750.104.881KM Edward Street,?0100000000000151960,Public LX,BW-03CR,duaringa,Blackwater,CL773
3,LX000640,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN,LX640.570.366KM Dart's Creek Road,?0100000000000151964,Public LX,BW-01CR,ambroseepala,Blackwater,NC457
4,LX000758,Asset Type Crossing,"Public Level Xing Refurbishment (signage, drai...",0.000,15,years,Single side km,NaN,LX758.581.401KM Gentle Annie Road,?0100000000000151959,Public LX,BW-01CR,epalaraglan,Blackwater,NC457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43079,ST008450-22,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN,RS/R54-I2 Isolator,?0100000000000209788,Isolators,BW-01CR,raglan,Blackwater,NC457
43080,ST008470-40,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN,861F/862A Isolator,?0100000000000210263,Isolators,BW-03CR,blackwater,Blackwater,CL777\nCL778
43081,ST008470-33,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN,BR/AT2-I Isolator,?0100000000000210256,Isolators,BW-03CR,blackwater,Blackwater,CL777\nCL778
43086,ST007820-04,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN,GR/AT1-I Isolator,?0100000000000207888,Isolators,BW-03CR,gracemere,Blackwater,CL404
43088,ST008530-04,Asset Type Oveahead,Overhead Line System,0.000,50,years,Tension length,NaN,852/8 Isolator,?0100000000000210342,Isolators,BW-03CR,umolo,Blackwater,CL773

In [11]:
model_testrun_1.to_pickle("DataFiles/nsap_renewal_assets_linked.pkl")

## Maintenance Link

## 5.  Read in "AllFLOCMaintenanceRequirementAndAVGCost" which is the entire pkl file provided by Huy Nguyen
    * (5) gets joined with the result for (2+3) along with (1) for tonnage
    * result is called nsap_maintenance_assets_linked
    * This is the file that needs to be replace with an updated version from Huy once he can run the script that converts Jane's linkage into his maintenance format. 
    * If the format isnt clear, review the existing "AllFLOCMaintenanceRequirementAndAVGCost" file and it will become familiar as to what the format needs to be

In [12]:
maintenance = pd.read_pickle("/workspaces/ds08-network-strategic-asset-plan-v2/AllFLOCMaintenanceRequirementAndAVGCost.pkl")
maintenance

,FLOC_TPLNR_FunctionalLocationInternalKey,FLOC_STRNO_FunctionalLocation,FLOC_PLTXT_FunctionalLocationDescr,FLOC_TYPTX_FunctionalLocationCategoryDescr,FLOC_EQART_TechnicalObjectType,FLOC_EARTX_TechnicalObjectTypeDescr,FLOC_BUKRS_CompanyCode,FLOC_STORT_Location,FLOC_STORT_LocationDescr,FLOCLIN_TPLNR_FunctionalLocationInternalKey,FLOCLIN_LINEAR_LENGTH_LinearLengthKM,Index,ActivityCode,Maintenance Product,Frequency Required,Frequency Unit,TechnicalObjects,Specifics,TechnicalObjects_split,AverageCost
0,?0100000000000387769,AC-01CH,CALLEMONDAH BLUE ROAD 1,Track,10003,Yard Track,5000,CA0089,Callemondah,?0100000000000387769,0.179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,?0100000000000365741,AC-01JN,Jilalan Provisioning 1,Track,10003,Yard Track,5000,JI0204,Jilalan,?0100000000000365741,4.864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,?0100000000000366347,AC-01JN-JNJN,Jilalan Provisioning 1,Track,999999,Lvl 3 Segmentation,5000,JI0204,Jilalan,?0100000000000366347,4.864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,?0100000000000377748,AC-01NA,NOGOA YARD BLUE ROAD TRACK 1,Track,10003,Yard Track,5000,NO0275,Nogoa-Yamala,?0100000000000377748,1.604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,?0100000000000377748,AC-01NA,NOGOA YARD BLUE ROAD TRACK 1,Track,10003,Yard Track,5000,NO0275,Nogoa-Yamala,?0100000000000377748,1.604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400122,?0100000000000265380,XX100013-01,Bridge 9.280km TRACK 1,Bridges and other Structures,20010,Bridges,5000,,None,?0100000000000265380,0.000,1.0,B05,Steel Bridge Repairs,NaN,Condition Dependent,Bridges,We only have 1 Steel Bridge,Bridges,NaN
400123,?0100000000000265380,XX100013-01,Bridge 9.280km TRACK 1,Bridges and other Structures,20010,Bridges,5000,,None,?0100000000000265380,0.000,1.0,B06,Timber Bridge Repairs,NaN,Condition Dependent,Bridges,We have 0 timber bridges,Bridges,NaN
400124,?0100000000000265380,XX100013-01,Bridge 9.280km TRACK 1,Bridges and other Structures,20010,Bridges,5000,,None,?0100000000000265380,0.000,1.0,B04,Concrete Bridge Repairs,NaN,Condition Dependent,Bridges,NaN,Bridges,7593.577777
400125,?0100000000000265380,XX100013-01,Bridge 9.280km TRACK 1,Bridges and other Structures,20010,Bridges,5000,,None,?0100000000000265380,0.000,1.0,B05,Steel Bridge Repairs,NaN,Condition Dependent,Bridges,We only have 1 Steel Bridge,Bridges,NaN
400126,?0100000000000265380,XX100013-01,Bridge 9.280km TRACK 1,Bridges and other Structures,20010,Bridges,5000,,None,?0100000000000265380,0.000,1.0,B06,Timber Bridge Repairs,NaN,Condition Dependent,Bridges,We have 0 timber bridges,Bridges,NaN

In [13]:
model_testrun_2 = pd.merge(maintenance, complete, on = "FLOC_STRNO_FunctionalLocation", how = "left")
model_testrun_2.loc[(model_testrun_2["LineCode"].notnull())&(model_testrun_2["ActivityCode"].notnull())] #this doesnt store the output so nulls still included
model_testrun_2.columns

Index(['FLOC_TPLNR_FunctionalLocationInternalKey_x',
       'FLOC_STRNO_FunctionalLocation', 'FLOC_PLTXT_FunctionalLocationDescr_x',
       'FLOC_TYPTX_FunctionalLocationCategoryDescr',
       'FLOC_EQART_TechnicalObjectType',
       'FLOC_EARTX_TechnicalObjectTypeDescr_x', 'FLOC_BUKRS_CompanyCode',
       'FLOC_STORT_Location', 'FLOC_STORT_LocationDescr_x',
       'FLOCLIN_TPLNR_FunctionalLocationInternalKey',
       'FLOCLIN_LINEAR_LENGTH_LinearLengthKM', 'Index', 'ActivityCode',
       'Maintenance Product', 'Frequency Required', 'Frequency Unit',
       'TechnicalObjects', 'Specifics', 'TechnicalObjects_split',
       'AverageCost', 'FLOC_PLTXT_FunctionalLocationDescr_y',
       'FLOC_TPLNR_FunctionalLocationInternalKey_y',
       'FLOC_EARTX_TechnicalObjectTypeDescr_y',
       'FLOC_MSGRP_FunctionalLocationRoom', 'FLOC_STORT_LocationDescr_y',
       'System', 'LineCode'],
      dtype='object')

In [14]:
model_testrun_2.to_pickle("DataFiles/nsap_maintenance_assets_linked.pkl")